apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: YWlybGluZXM=   # airlines encodé en base64
  mongo-root-password: YWlybGluZXM=   # airlines encodé en base64
